kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: xmorse/drone-changeset
      username: xmorse
      tags: 
      - latest
      - 0.0.0
      password:
        from_secret: docker_password
